name: Continuous Delivery

on:
    push:
        branches:
          - develop
 
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:             
        -  
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
 
        -   name: Login in to registry
            uses: docker/login-action@v2
            with:
                registry: https://index.docker.io/v1/
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        - 
            name: Build and push container image to registry
            uses: docker/build-push-action@v6 
            with: 
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple-api-java:${{ github.sha }}'
                file: ./Dockerfile

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - 
            name: Deploy to Azure Web App
            id: deploy-to-webapp
            uses: azure/webapps-deploy@v2
            with:
              app-name: fiap-simple-api-dev-98516
              publish-profile: ${{ secrets.AZURE_PROFILE }}
              images: 'ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/simple-api-java:${{ github.sha }}'